deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp -R colorlib-regform-7 $DEPLOYPATH    
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp pro.js $DEPLOYPATH
    
